### ISSUE TITLE
第一阶段目标

### ISSUE THREAD

**Issue by membphis** [api7/apisix-mesh-agent#1]
第一阶段目标为实现一个位于数据面的 agent 进程，以 agent 进程 + APISIX 为一个整体，作为服务网格的数据面，对接 Istio 等控制面。

**目标**：支持根据 uri 转发 HTTP 请求。
**启动时间：** 2021 年 2 月 18 号。

- [x] 【补充结构图】 + 文档（高优先级）
- [x] agent 项目 bootstrap，基础库（1个工作日）
~~- [ ] 支持 xDS（v2）协议，基于此转换出 APISIX 的 Route、Upstream 等资源（10个工作日）。~~
- [x] 支持模拟 etcd 协议，从而可以让 APISIX watch 本地的 agent（10 个工作日）
- [x] readdir
- [x] watch
- [x] fake create dir
- [x] APISIX 支持获取原始端口信息（在流量被 iptables 拦截以后） 
- [x] 测试
- [x] 明确安装部署方式（二进制文件，apisix mesh + istio 可以一起工作）
- [ ] 逐步制定 roadmap 内容

第一阶段完成时，agent + apisix 应当可以在有一个控制面对接的情况下良好工作。

**Comment by tokers** [comment]
Done.
