### ISSUE TITLE
etcdv3 portion may be separated into individual projects ?

### ISSUE THREAD

**Issue by zhixiongdu027** [api7/apisix-mesh-agent#68]
I think the etcdv3 part may be very useful for third-party development, such as when a third-party developer needs to read the configuration from MySql, multiple text files.

**Comment by tokers** [comment]
@adugeek Indeed we have this plan. @tao12345666333

**Comment by adugeek** [comment]
Wow,That' Great!

**Comment by tao12345666333** [comment]
@adugeek  new project here https://github.com/api7/etcd-adapter

The relevant code @tokers  is being moved to this project.
