### ISSUE TITLE
Support as a istio gateway

### ISSUE THREAD

**Issue by Patrick0308** [api7/apisix-mesh-agent#80]
In a mesh, there are not only east-west traffic but also north-south traffic. In many cases, we feel that istio is not strong in managing north-sourth traffic. I hope apisix can enhance it as a istio gateway.

**Comment by ccwxl** [comment]
kong 目前好像支持. https://konghq.com/blog/istio-gateway/

**Comment by membphis** [comment]
you can take a look:

English:
https://apisix.apache.org/blog/2021/12/17/exposure-istio-with-apisix-ingress/

Chinese:
https://apisix.apache.org/zh/blog/2021/12/17/exposure-istio-with-apisix-ingress
